// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddKeyword(arg1:string):Promise<void>;

export function AddToAllowlist(arg1:string):Promise<void>;

export function AddToBlocklist(arg1:string):Promise<void>;

export function CACertPath():Promise<string>;

export function ConfirmQuit(arg1:string):Promise<void>;

export function DisableProtection(arg1:string):Promise<void>;

export function EnableProtection():Promise<void>;

export function GetAdvancedSettings():Promise<main.AdvancedSettings>;

export function GetAllowlist():Promise<Array<string>>;

export function GetBlocklist():Promise<main.BlocklistData>;

export function GetContentSettings():Promise<main.ContentSettings>;

export function GetDisableDelayStatus():Promise<main.DisableDelayStatus>;

export function GetFocusMode():Promise<main.FocusModeStatus>;

export function GetKeywords():Promise<main.KeywordsData>;

export function GetProxySettings():Promise<main.ProxySettings>;

export function GetStatus():Promise<main.Status>;

export function HasPassword():Promise<boolean>;

export function InstallCACert():Promise<void>;

export function RemoveFromAllowlist(arg1:string):Promise<void>;

export function RemoveFromBlocklist(arg1:string):Promise<void>;

export function RemoveKeyword(arg1:string):Promise<void>;

export function RequestDisable():Promise<void>;

export function SaveAdvancedSettings(arg1:string,arg2:main.AdvancedSettings):Promise<void>;

export function SaveContentSettings(arg1:string,arg2:main.ContentSettings):Promise<void>;

export function SaveProxySettings(arg1:main.ProxySettings):Promise<void>;

export function SetPassword(arg1:string,arg2:string):Promise<void>;

export function StartFocusMode(arg1:number):Promise<void>;

export function Uninstall(arg1:string):Promise<void>;

export function VerifyPassword(arg1:string):Promise<boolean>;
