// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFocusSite(arg1) {
  return window['go']['main']['App']['AddFocusSite'](arg1);
}

export function AddKeyword(arg1) {
  return window['go']['main']['App']['AddKeyword'](arg1);
}

export function AddToAllowlist(arg1) {
  return window['go']['main']['App']['AddToAllowlist'](arg1);
}

export function AddToBlocklist(arg1) {
  return window['go']['main']['App']['AddToBlocklist'](arg1);
}

export function CACertPath() {
  return window['go']['main']['App']['CACertPath']();
}

export function ClearStats() {
  return window['go']['main']['App']['ClearStats']();
}

export function ConfirmQuit(arg1) {
  return window['go']['main']['App']['ConfirmQuit'](arg1);
}

export function DisableProtection(arg1) {
  return window['go']['main']['App']['DisableProtection'](arg1);
}

export function EnableProtection() {
  return window['go']['main']['App']['EnableProtection']();
}

export function GetAdvancedSettings() {
  return window['go']['main']['App']['GetAdvancedSettings']();
}

export function GetAllowlist() {
  return window['go']['main']['App']['GetAllowlist']();
}

export function GetBlocklist() {
  return window['go']['main']['App']['GetBlocklist']();
}

export function GetContentSettings() {
  return window['go']['main']['App']['GetContentSettings']();
}

export function GetDisableDelayStatus() {
  return window['go']['main']['App']['GetDisableDelayStatus']();
}

export function GetFocusMode() {
  return window['go']['main']['App']['GetFocusMode']();
}

export function GetFocusSites() {
  return window['go']['main']['App']['GetFocusSites']();
}

export function GetKeywords() {
  return window['go']['main']['App']['GetKeywords']();
}

export function GetProxySettings() {
  return window['go']['main']['App']['GetProxySettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTimeRestrictions() {
  return window['go']['main']['App']['GetTimeRestrictions']();
}

export function HasPassword() {
  return window['go']['main']['App']['HasPassword']();
}

export function InstallCACert() {
  return window['go']['main']['App']['InstallCACert']();
}

export function RemoveFocusSite(arg1) {
  return window['go']['main']['App']['RemoveFocusSite'](arg1);
}

export function RemoveFromAllowlist(arg1) {
  return window['go']['main']['App']['RemoveFromAllowlist'](arg1);
}

export function RemoveFromBlocklist(arg1) {
  return window['go']['main']['App']['RemoveFromBlocklist'](arg1);
}

export function RemoveKeyword(arg1) {
  return window['go']['main']['App']['RemoveKeyword'](arg1);
}

export function RequestDisable() {
  return window['go']['main']['App']['RequestDisable']();
}

export function SaveAdvancedSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveAdvancedSettings'](arg1, arg2);
}

export function SaveContentSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveContentSettings'](arg1, arg2);
}

export function SaveProxySettings(arg1) {
  return window['go']['main']['App']['SaveProxySettings'](arg1);
}

export function SaveTimeRestrictions(arg1) {
  return window['go']['main']['App']['SaveTimeRestrictions'](arg1);
}

export function SetFilterLevel(arg1) {
  return window['go']['main']['App']['SetFilterLevel'](arg1);
}

export function SetFocusSiteActive(arg1, arg2) {
  return window['go']['main']['App']['SetFocusSiteActive'](arg1, arg2);
}

export function SetPassword(arg1, arg2) {
  return window['go']['main']['App']['SetPassword'](arg1, arg2);
}

export function StartFocusMode(arg1) {
  return window['go']['main']['App']['StartFocusMode'](arg1);
}

export function StopFocusMode(arg1) {
  return window['go']['main']['App']['StopFocusMode'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
